task 2
kattka1995/planer pull request #2
Opened 2021-10-25 12:02 UTC by kattka1995

2021-10-25 17:52 UTC, rinat-fatkhutdinov requested changes

2021-10-25 17:52 UTC, rinat-fatkhutdinov commented on src/main/java/common/TaskService.java
>                      break;
Этот break теперь лишний

2021-10-25 17:52 UTC, rinat-fatkhutdinov commented on src/main/java/common/TaskService.java
> +                    break;
аналогично. тоже лишний

2021-10-25 17:52 UTC, rinat-fatkhutdinov commented on src/main/java/common/TaskService.java
> +                    break;
Здесь тоже можно вынести break за оператор if

2021-10-25 17:52 UTC, rinat-fatkhutdinov commented on src/main/java/common/TaskService.java
> +                    break;
лишний

2021-10-25 17:52 UTC, rinat-fatkhutdinov commented on src/main/java/common/TaskService.java
>                  break;
здесь он уже просто бесполезен

2021-10-25 17:52 UTC, rinat-fatkhutdinov commented on src/main/java/common/TaskService.java
> +    private List<Task> tasks = new ArrayList<>();
Выбрать более подходящую коллекцию

2021-10-25 17:52 UTC, rinat-fatkhutdinov commented on src/main/java/common/TaskService.java
> +                    this.search(command.replaceFirst("^\\S*", "").trim());
`command.replaceFirst("^\\S*", "").trim()` используется более чем в 3х местах
Напрашивается рефактроринг

2021-10-25 17:52 UTC, rinat-fatkhutdinov commented on src/main/java/common/TaskService.java
> +                    this.search(command.replaceFirst("^\\S*", "").trim());
`this.` в подобных местах лишний

2021-10-25 17:52 UTC, rinat-fatkhutdinov commented on src/main/java/common/TaskService.java
> +    private int id = 0;
неговорящее название

2021-10-25 17:52 UTC, rinat-fatkhutdinov commented on src/main/java/common/TaskService.java
> +                        task.setId(taskId++);
В общем случае, при удалении элемента коллекции не ожидается изменение оставшихся в этой коллекции элементов. Изменение идентификаторов выглядит костылём, т.к. id используется как порядковый номер.

2021-10-25 17:52 UTC, rinat-fatkhutdinov commented on src/main/java/common/TaskService.java
> +                if (newDescription.contains("\\n")) {
Это вообще возможно, ввести несколько строк?
По ТЗ вижу ограничение только для add.

2021-10-25 17:52 UTC, rinat-fatkhutdinov commented on src/main/java/common/TaskService.java
> +        tasks.stream().filter(s -> s.getDescription().contains(desc.toLowerCase()))
почему к нижнему регистру приводится только строка для поиска?

2021-10-25 17:52 UTC, rinat-fatkhutdinov commented on src/main/java/common/TaskService.java
> +            tasks.stream().filter(s -> s.getStatus().equals(NOT_DONE)).forEach(k -> System.out.println((String.format("%s. [%s] %s", k.getId(), k.getStatus(),
print и printAll практически не отличаются. Реализовать в одном методе, исключив дублирование

2021-10-26 17:34 UTC, kattka1995 commented on src/main/java/common/TaskService.java
>                      break;
done

2021-10-26 17:39 UTC, kattka1995 commented on src/main/java/common/TaskService.java
> +                    break;
done

2021-10-26 17:40 UTC, kattka1995 commented on src/main/java/common/TaskService.java
> +                    break;
done

2021-10-26 17:40 UTC, kattka1995 commented on src/main/java/common/TaskService.java
> +                    break;
done

2021-10-26 17:40 UTC, kattka1995 commented on src/main/java/common/TaskService.java
>                  break;
done

2021-10-26 17:41 UTC, kattka1995 commented on src/main/java/common/TaskService.java
> +    private int id = 0;
done

2021-10-26 17:41 UTC, kattka1995 commented on src/main/java/common/TaskService.java
> +                        task.setId(taskId++);
done

2021-10-26 17:43 UTC, kattka1995 commented on src/main/java/common/TaskService.java
> +                if (newDescription.contains("\\n")) {
done, убрала проверку на \n для метода edit

2021-10-26 17:43 UTC, kattka1995 commented on src/main/java/common/TaskService.java
> +        tasks.stream().filter(s -> s.getDescription().contains(desc.toLowerCase()))
done

2021-10-26 18:59 UTC, kattka1995 commented on src/main/java/common/TaskService.java
> +            tasks.stream().filter(s -> s.getStatus().equals(NOT_DONE)).forEach(k -> System.out.println((String.format("%s. [%s] %s", k.getId(), k.getStatus(),
Поправила, но не уверена, что правильно

2021-10-27 11:29 UTC, kattka1995 commented on src/main/java/common/TaskService.java
> +    private List<Task> tasks = new ArrayList<>();
done

2021-10-27 11:29 UTC, kattka1995 commented on src/main/java/common/TaskService.java
> +                    this.search(command.replaceFirst("^\\S*", "").trim());
done

2021-10-27 11:34 UTC, rinat-fatkhutdinov requested changes

2021-10-27 11:34 UTC, rinat-fatkhutdinov commented on src/main/java/common/TaskService.java
> +            if (tasks.get(taskId) == null)
этот if и последующий else-if выполняют одно и тоже - рефакторинг

2021-10-27 11:34 UTC, rinat-fatkhutdinov commented on src/main/java/common/TaskService.java
> +            if (tasks.get(taskId) == null)
вместо `tasks.get(taskId) == null` нужно воспользоваться подходящим методом contains

2021-10-27 11:34 UTC, rinat-fatkhutdinov commented on src/main/java/common/TaskService.java
> +            if (tasks.get(taskId) == null)
тут тоже get лучше заменить

2021-10-27 11:34 UTC, rinat-fatkhutdinov commented on src/main/java/common/TaskService.java
> +            else if (tasks.get(taskId).getStatus() == DONE) {
В данном случае статус вроде всегда не null, но вместо == лучше equals. Вдруг бага, или код поменятся

2021-10-27 11:34 UTC, rinat-fatkhutdinov commented on src/main/java/common/TaskService.java
> +                .forEach(k -> System.out.println(String.format("%s. [%s] %s", k.getKey(), k.getValue().getStatus(),
`String.format` в `System.out.println` лишний, println точно также умеет форматировать вывод

2021-10-27 11:34 UTC, rinat-fatkhutdinov commented on src/main/java/common/TaskService.java
> +                .forEach(k -> System.out.println(String.format("%s. [%s] %s", k.getKey(), k.getValue().getStatus(),
`System.out.println(String.format("%s. [%s] %s", k.getKey(), k.getValue().getStatus(), k.getValue().getDescription()))` встречается дважды(а по факту трижды) - рефакторинг

2021-10-27 11:34 UTC, rinat-fatkhutdinov commented on src/main/java/common/TaskService.java
> +            if (tasks.get(taskId) == null)
тоже лучше воспользоваться более подходящим методом класса Map

2021-10-27 11:34 UTC, rinat-fatkhutdinov commented on src/main/java/common/TaskService.java
> +            tasks.entrySet().stream().map(task -> String.format("%s. [%s] %s", task.getKey(), task.getValue().getStatus(),
в разных ветках вывод осуществляется одинаковый, но используются разные конструкции. Можно сделать одинаково.

2021-10-27 11:34 UTC, rinat-fatkhutdinov commented on src/main/java/common/TaskService.java
> +    public void print(String... all) {
`String... all` избыточен, достаточно boolean аргумента

2021-10-28 06:49 UTC, kattka1995 commented on src/main/java/common/TaskService.java
> +            else if (tasks.get(taskId).getStatus() == DONE) {
done

2021-10-28 06:56 UTC, kattka1995 commented on src/main/java/common/TaskService.java
> +            if (tasks.get(taskId) == null)
done

2021-10-28 06:56 UTC, kattka1995 commented on src/main/java/common/TaskService.java
> +            if (tasks.get(taskId) == null)
done

2021-10-28 06:57 UTC, kattka1995 commented on src/main/java/common/TaskService.java
> +            if (tasks.get(taskId) == null)
done

2021-10-28 08:51 UTC, kattka1995 commented on src/main/java/common/TaskService.java
> +    public void print(String... all) {
done

2021-10-28 08:52 UTC, kattka1995 commented on src/main/java/common/TaskService.java
> +            tasks.entrySet().stream().map(task -> String.format("%s. [%s] %s", task.getKey(), task.getValue().getStatus(),
done

2021-10-28 08:52 UTC, kattka1995 commented on src/main/java/common/TaskService.java
> +                .forEach(k -> System.out.println(String.format("%s. [%s] %s", k.getKey(), k.getValue().getStatus(),
done

2021-10-28 10:24 UTC, rinat-fatkhutdinov approved these changes
хорошо. по мелочи можно поправить

2021-10-28 10:24 UTC, rinat-fatkhutdinov commented on src/main/java/common/TaskService.java
> +    private String replaceCommandName (String str){
replace на что - непонятно, что возвращает - не понятно. Суть метода извлечь аргументы?)

2021-10-28 10:24 UTC, rinat-fatkhutdinov commented on src/main/java/common/TaskService.java
> +            else if (tasks.get(taskId).getStatus()) {
можно в одну строку типа `tasks.get(taskId).setStatus(!tasks.get(taskId).getStatus())`
Ну или в две, чтоб лучше читалось, но if-else здесь избыточен

2021-10-28 10:36 UTC, kattka1995 commented on src/main/java/common/TaskService.java
> +            else if (tasks.get(taskId).getStatus()) {
done

2021-10-28 10:38 UTC, kattka1995 commented on src/main/java/common/TaskService.java
> +    private String replaceCommandName (String str){
да 🙃

2021-10-28 10:43 UTC, merged